# Generated by Django 4.1.13 on 2023-11-02 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 2, 7, 44, 28, 185713, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
