# Generated by Django 4.1.13 on 2023-11-07 20:04

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="about_me",
            field=models.TextField(
                default="Say something about yourself", verbose_name="AboutMe"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default=8801521325067,
                max_length=30,
                region=None,
                verbose_name="PhoneNumber",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_photo",
            field=models.ImageField(
                default="/profile_default.png",
                upload_to="",
                verbose_name="ProfilePhoto",
            ),
        ),
    ]
